# Generated by Django 2.1.5 on 2019-06-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification'),
        ('teams', '0003_auto_20190616_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='account',
        ),
        migrations.AddField(
            model_name='skill',
            name='account',
            field=models.ManyToManyField(related_name='skills', to='accounts.Profile'),
        ),
    ]
