# Generated by Django 2.1.5 on 2019-06-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20190616_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='desired_skills',
            field=models.ManyToManyField(related_name='desires_skills', to='teams.Skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='project',
            field=models.ManyToManyField(related_name='desired_skills', to='teams.Project'),
        ),
    ]
