# Generated by Django 2.1.5 on 2019-06-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20190617_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='desired_skills',
        ),
        migrations.AlterField(
            model_name='skill',
            name='project',
            field=models.ManyToManyField(related_name='desired_skills', to='teams.Position'),
        ),
    ]
