# Generated by Django 2.1.5 on 2019-06-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification'),
        ('teams', '0007_auto_20190617_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='rejects',
            field=models.ManyToManyField(related_name='rejects', to='accounts.Profile'),
        ),
    ]
