# Generated by Django 2.1.5 on 2019-06-18 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_position_rejects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='incumbent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='accounts.Profile'),
        ),
    ]
